// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvThKNRNVH6J2RflAOWXHgTrkCOhGlpOQ',
    appId: '1:429615468598:web:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '429615468598',
    projectId: 'su-takip-app',
    authDomain: 'su-takip-app.firebaseapp.com',
    storageBucket: 'su-takip-app.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvThKNRNVH6J2RflAOWXHgTrkCOhGlpOQ',
    appId: '1:429615468598:android:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '429615468598',
    projectId: 'su-takip-app',
    storageBucket: 'su-takip-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvThKNRNVH6J2RflAOWXHgTrkCOhGlpOQ',
    appId: '1:429615468598:ios:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '429615468598',
    projectId: 'su-takip-app',
    storageBucket: 'su-takip-app.appspot.com',
    iosBundleId: 'com.example.suu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvThKNRNVH6J2RflAOWXHgTrkCOhGlpOQ',
    appId: '1:429615468598:macos:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '429615468598',
    projectId: 'su-takip-app',
    storageBucket: 'su-takip-app.appspot.com',
    iosBundleId: 'com.example.suu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvThKNRNVH6J2RflAOWXHgTrkCOhGlpOQ',
    appId: '1:429615468598:windows:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '429615468598',
    projectId: 'su-takip-app',
    storageBucket: 'su-takip-app.appspot.com',
  );
}
